security:
  oauth2:
    client:
      clientId: ${ms.clientId}
      clientSecret: ${ms.clientSecret}
      # From Authorization Server's metadata
      accessTokenUri: https://login.microsoftonline.com/${ms.tenant}/oauth2/v2.0/token
      userAuthorizationUri: https://login.microsoftonline.com/${ms.tenant}/oauth2/v2.0/authorize
      clientAuthenticationScheme: form
      scope:
        - openid
        - profile
        - email
    resource:
      # from your Auth Server's metadata, check .well-known/openid-configuration
      # if not in .well-known/oauth-authorization-server
      userInfoUri: https://graph.microsoft.com/me
      jwk:
        key-set-uri: https://login.microsoftonline.com/${ms.tenant}/discovery/v2.0/keys
      #preferTokenInfo: false
server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
